export const UPDATE_GAME = "updateGame";
export const SOCKET_CONNECT = "SOCKET_CONNECT";
export const SOCKET_UPDATE = "SOCKET_UPDATE";
export const SOCKET_DISCONNECT = "SOCKET_DISCONNECT";
export const SOCKET_PLAYER_JOIN = "SOCKET_PLAYER_JOIN";
